### ISSUE TITLE
i can't login

### ISSUE THREAD

**Issue by StokerBram** [JheyluisReyes/AuthForm#1]
i installed python correctly and every time i try to log in it tells me that the user and pass are invalid
![Untitled](https://github.com/JheyluisReyes/AuthForm/assets/84342028/9e2a78d6-14c5-4e5c-a713-6cdf56aa80b7)

**Comment by JheyluisReyes** [comment]
Hello **StokerBram**, the application notifies you that the Username and Password are invalid because my Username and Password are reflected within the Application code, so that you can Login with your data, you must modify the code from the **line 14**, I hope I have helped you.

![Untitled](https://github.com/JheyluisReyes/AuthForm/assets/141370176/78387689-a55e-477d-b500-67bc2c30b977)

**Comment by StokerBram** [comment]
> Hello **StokerBram**, the application notifies you that the Username and Password are invalid because my Username and Password are reflected within the Application code, so that you can Login with your data, you must modify the code from the **line 14**, I hope I have helped you.
> 
> ![Untitled](https://user-images.githubusercontent.com/141370176/259779525-78387689-a55e-477d-b500-67bc2c30b977.PNG)

so, do you mean that i can directly enter my data or i can connect it with a database?

**Comment by JheyluisReyes** [comment]
Yes, you can enter your data or directly connect it to a Database.

**Comment by StokerBram** [comment]
> Yes, you can enter your data or directly connect it to a Database.

oh ok thank you very much
